extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  release:
    build:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat ../../VERSION)
        name: changelog
      - comment: call CloudBees Flow to run a release
        sh: curl https://ps9.ecloud-kdemo.com/rest/v1.0/jobs
        name: cloudbees-flow-release
