extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  release:
    build:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat ../../VERSION)
        name: changelog
      - sh: export FLOW_TOKEN="$(jx step credential -s flow-token -k token)"
        name: store-pwd
      - comment: call CloudBees Flow to run a release
        sh: >
          curl -X POST --header "Authorization: Basic $FLOW_TOKEN" --header "Content-Type: application/json" --header "Accept: application/json" -d "{}" "https://ps9.ecloud-kdemo.com/rest/v1.0/pipelines?pipelineName=jhendrick_pipeline&projectName=Training_jhendrick" --insecure
        name: cloudbees-flow-release
