extends:
  import: classic
  file: maven/pipeline.yaml
pipelines:
  release:
    build:
      steps:
      - sh: jx step post build --image $DOCKER_REGISTRY/$ORG/$APP_NAME:\$(cat VERSION)
        name: post-build
    promote:
      steps:
      - sh: jx step changelog --version v\$(cat ../../VERSION)
        name: changelog
      - sh: export FLOW_TOKEN="$(jx step credential -s flow-token -k token)"; echo $FLOW_TOKEN
        name: store-pwd
      - sh: echo $FLOW_TOKEN
        name: echo-token       
      - comment: call CloudBees Flow to run a release
        sh: >
          curl -H "Authorization: Basic $FLOW_TOKEN" https://ps9.ecloud-kdemo.com/rest/v1.0/jobs --insecure
        name: cloudbees-flow-release
